### PR TITLE
added schema generation doc

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
CC: @macrogreg @jpiyali @iusafaro

**Comment by macrogreg** [comment]
Thank you, @SergeyKanzhelev .
I was also documenting my steps in order to turn them into a manual a the end. However, I have not completed yet. I am currently blocked on merging @jpiyali 's PR that addresses a bond build issue (the duplicating field IDs turned out to break the build):
https://github.com/Microsoft/ApplicationInsights-Home/pull/198
Could you please approve it?
I can then merge and proceed. Thanks.

**Comment by SergeyKanzhelev** [comment]
Please contribute into this doc. Too many questions recently about it

**Comment by macrogreg** [comment]
> Please contribute into this doc. Too many questions recently about it

Sure, @SergeyKanzhelev . If I will note anything down that is not already there, I will add it.

**Pull request merged**
