### PR TITLE
add a readme.md file

### PR DESCRIPTION
**Pull request by barustum**
adding a readme.md file with contributor license.

### CODE REVIEW

**Comment by dnduffy** [comment]
:shipit:
(if the message with "radme.md" can be tweaked that would be great)

**Comment by barustum** [comment]
Thanks David. Oops, my bad. Not sure how I can change a commit message. I'll take a look if possible.

**Comment by barustum** [comment]
I'll abandon the branch and create a new one with a proper commit message.

**Comment by barustum** [comment]
@dnduffy Done.

**Pull request merged**
