### PR TITLE
Add optional param: eventDateTime, for past events

### PR DESCRIPTION
**Pull request by dmitrygershman**
In my case i wanted to back-fill deployment annotations for last 3 months, so this change allows to do that.
Parameter is optional so its backwards compatible.

and, thanks for the script! :)

Dima

### CODE REVIEW

**Comment by dnduffy** [comment]
:shipit:

**Comment by SergeyKanzhelev** [comment]
I'm not sure backend will support any range of time. @barustum - do you know how far back and forward you can set a date?

**Comment by dmitrygershman** [comment]
Good point.
I tried it for 2 months back and it worked just fine.
Maybe its limited to the same data retention policy as Metrics Explorer,
where annotations are presented...

**Comment by jpiyali** [comment]
@dmitrygershman , thanks for suggesting the change with the optional datetime input. Currently, we don't limit users from creating annotations with a past date, but it wouldn't be useful for more than 90 days as that is the max time range that we support querying data. Also, in future we may reduce this time range with some storage model changes that we are planning.

For now, could you please update the pull request to default to current behavior if date is older than 90 days. Thanks a lot!

**Comment by dmitrygershman** [comment]
Hi
Then, how about throwing an error in case the date is older than 90 days?

Creating annotation with current date in such case is not what script user
would expect, and it would create unwanted annotation in ME (Metrics
Explorer).

Or, maybe since you don't limit users from creating annotations with a past
date, we can leave it as is?

Thanks
Dima

**Comment by abgreg** [comment]
Hey @dmitrygershman,

I think that you and @jpiyali are in agreement here: the best solution would be to throw an error when the user attempts to create an annotation with a date more than 90 days ago.

In my opinion, this is better than allowing the user to create older, unusable annotations, since it is so clear with the user upfront.

Thanks,
Abby

**Comment by jpiyali** [comment]
Thanks for the updates @dmitrygershman.
@SergeyKanzhelev - could you please merge the pull requests? I don't have permissions.

**Comment by SergeyKanzhelev** [comment]
Thanks @dmitrygershman!

**Pull request merged**
